### ISSUE TITLE
resilient db

### ISSUE THREAD

**Issue by remexre** [project-domino/project-domino#39]
Right now, the docker build fails immediately because the DB takes longer to start than the application. Ideally, we wouldn't fail on these errors, and instead would get (503) errors instead of termination. Intermittent downtime (e.g. during an upgrade) would therefore not require restarting the entire infrastructure, but only one application.

**Comment by akshay288** [comment]
The server now returns 500s if there is no db, I can change that to 503s.

Keep on trying until there is no error?

```
opened := false
for !opened {
    var err error
     db.DB, err = gorm.Open(
        viper.GetString("database.type"),
        viper.GetString("database.url"),
    )
    opened = err == nil
    time.Sleep(time.Second)
}
```

**Comment by remexre** [comment]
The server fails to start if there's no db...?

**Comment by akshay288** [comment]
The way it is currently layed out (with SetupDatabase) We would definitely want a db before starting the server. I can make a a SQL script to setup the database if you would like

This is what it is now:

```
var err error
db.DB, err = gorm.Open(
    viper.GetString("database.type"),
    viper.GetString("database.url"),
)
Must(err)
```

**Comment by remexre** [comment]
No, but if the DB server starts after the web server starts, the web server fails

**Comment by remexre** [comment]
Why shouldn't the web server be able to start and e.g. serve an API version endpoint with no DB?

**Comment by akshay288** [comment]
It can if we setup the database somewhere else

**Comment by remexre** [comment]
?

**Comment by remexre** [comment]
Right now, the server running PostgreSQL and the server running domino are basically two machines on the same network. That way, if either needs to be scaled, we can scale them separately. Conversely, if one fails, the other shouldn't. Right now, the server can handle db failure once it's up, but fails to init. Not sure if this can be fixed by Gorm, but if not... Redis uses connection pools created on-demand, so it doesn't fail completely?
