### ISSUE TITLE
Should login be allowed with email?

### ISSUE THREAD

**Issue by remexre** [project-domino/project-domino#42]
If we're only collecting email for notification purposes, should we make it optional and not have authentication with it?

**Comment by akshay288** [comment]
Its implemented serverside

**Comment by remexre** [comment]
Should it though?

**Comment by akshay288** [comment]
its done like that now

**Comment by remexre** [comment]
I'm asking whether it'd make more sense to make email purely for contact, rather than for login

**Comment by akshay288** [comment]
Sorry, I read your first post wrong. It is only used for contact right now.
